### ISSUE TITLE
The performance so slow when I click check button. the app server loading very long and request time out

### ISSUE THREAD

**Issue by VoHongHuy** [jorgediaz-lr/index-checker#14]

**Comment by jorgediaz-lr** [comment]
Hi @VoHongHuy 

Can you give me more information?

Did you try narrowing user interface options (for example checking only one specific Site or entity)

Do you have any log information?

**Comment by VoHongHuy** [comment]
Hi @jorgediaz-lr ,

Thanks for the reply. So app Liferay setup cluster-aware, time out for request 3600s
Yes I do as your step 
About log, I do  not see that any the log which need the doubt

**Comment by jorgediaz-lr** [comment]
Hi @VoHongHuy 

That log trace is not complete, can you attach the full log file?

Did you try narrowing user interface options (for example checking only one specific Site or entity)

Please, try selection only one site or only one entity.

**Comment by VoHongHuy** [comment]
Hi @jorgediaz-lr ,
About the security, I can not send full log for you
I have to try changes the option on form but still, request time out for app. Maybe my web server need to config the extra time out

**Comment by jorgediaz-lr** [comment]
Hi @VoHongHuy 

It is not necessary to attach the full log, but at least you should attach the full exception trace. Can you attach it?

Thank you

**Comment by VoHongHuy** [comment]
Hi @jorgediaz-lr ,

This is the capture log when I click check button on the form
![screenshot--2019 05 10-15-50-50](https://user-images.githubusercontent.com/43428724/57515012-e3957b80-733b-11e9-8c93-806a2710a0ab.jpg)

**Comment by jorgediaz-lr** [comment]
Hi @VoHongHuy 

As the error **is java.lang.OutOfMemoryError** your problem is you are running out of memory, you have to configure more memory in your Liferay installation

Regards,
Jorge
